[file_types]
image = jpg, jpeg, png, gif, tif, bmp, svg, webp
video = mp4, avi, wmv, mov, mpeg, mkv
audio = mp3, wav, aac, ogg, flac, midi
document = docx, pdf, txt, odt, doc
presentation = pptx, odp, ppt
spreadsheet = xlsx, csv, ods, xls
archive = zip, rar, 7z, tar, gz
font = ttf, otf
executable = exe
other = 

[settings]
# Using a local LLM
ai_mode = true
ai_server = 

# Set to 'shortcut', 'rename' or 'move'
operation_mode = shortcut

# Set to 'true' to prevent any file operations
dry_run = false

# Set the destination path for your renamed files, if mode is not set to 'rename'
# Default destination is the parent folder of your source directory
destination = 