[file_types]
image = jpg, jpeg, png, gif, tif, bmp, svg, webp
video = mp4, avi, wmv, mov, mpeg, mkv
audio = mp3, wav, aac, ogg, flac, midi
document = docx, pdf, txt, odt, doc
presentation = pptx, odp, ppt
spreadsheet = xlsx, csv, ods, xls
archive = zip, rar, 7z, tar, gz
font = ttf, otf
executable = exe
other = 

[settings]
# Use a local or online LLM to automatically organise and rename your chosen directory
ai_mode = true
ai_categorisation = true
ai_server = http://localhost:1234/v1
ai_model = google/gemma-3-4b

# Options:
# - shortcut -> 
# - rename
# - organise
# - 
operation_mode = shortcut

# Set to 'true' to prevent any file operations
dry_run = false

# Set the destination path for your renamed files, if mode is not set to 'rename'
# Default destination is the parent folder of your source directory
destination = 